### ISSUE TITLE
Peacock - xml validation error

### ISSUE THREAD

**Issue by Jeeppler** [JustusAvramenko/delenda_est#1]
While creating, interacting and killing the peacock I got an xml validation error for the peacock model. 

Mod Version: 0 A.D. Delenda Est released for Alpha 21

**Comment by Jeeppler** [comment]
I played the Mauryan fraction.

**Comment by JustusAvramenko** [comment]
Thank you for this. That error was corrected by me and then added to the public mod by Enrique in his big New Years art commit.
