### ISSUE TITLE
Main Menu Music is Copyrighted

### ISSUE THREAD

**Issue by psypherium** [JustusAvramenko/delenda_est#16]
![Screenshot from 2019-07-18 03-32-07](https://user-images.githubusercontent.com/12213882/61397311-f9f81e80-a90c-11e9-8596-0ef206e16c46.png)

**Comment by JustusAvramenko** [comment]
I received permission to use their music in the mod, so I don't know why they are copyrighting it like that. Luckily, you receive no copyright strike on your account so the video can still have the song in it, the video just can't be monetized.

**Comment by psypherium** [comment]
I think the claim was an automatic machine match, I don't think it was done manually.

It cannot be monetised by me, but it is being monetised by the musician. which means it is the only video on my channel which has an advertisement.

If my channel is ever monetised, I would like to split off some of the revenue of 0ad videos to the 0ad dev team, and some for Omhri for the main soundtrack. And some for the community, maybe some money for a tournament prize. Some for you for this mod too, but I cannot find a place to do that. Also, I will probably never achieve YouTube monetisation lol.

It's not a big problem, I muted those parts of the video and the claim disappeared.

**Comment by psypherium** [comment]
![Screenshot from 2019-12-30 12-54-09](https://user-images.githubusercontent.com/12213882/71565531-9735c080-2b03-11ea-9ce5-3813514ff669.png)


This is a waste of time and very annoying. Closed source games do not have this problem....

**Comment by psypherium** [comment]
![Screenshot from 2019-12-30 13-15-16](https://user-images.githubusercontent.com/12213882/71565840-a10cf300-2b06-11ea-8e59-45b35d19715b.png)

I must return to the video 3 separate times to fix the audio. I do not have time for this. I cannot create Delenda Est content until this situation is rectified.

**Comment by JustusAvramenko** [comment]
@psypherium Thanks for the comments bro. I agree with everything you say. I suspect the musicians give permission for almost any project to use their music so that they can rake in the ad revenue. This isn't necessary a bad thing: they get ad revenue, we get nice music, but I do understand how it affects your channel. My funds are currently limited, or I'd offer to purchase exclusive rights for the piece, since it's so good.
