### ISSUE TITLE
make this work with millennium 0 AD mod

### ISSUE THREAD

**Issue by ghost** [JustusAvramenko/delenda_est#25]
byzantine has a nice looking stables in the files yet no stables in vanilla! ;P 
i prefer a tradition RTS gameplay like AOE DE so this mod i like! but needs byzantine empire! :D

**Comment by JustusAvramenko** [comment]
I will eventually add a "Late Romans"/"Early Byzantines"/Dominate Romans-era civ at some point, that way the 3 major eras of the Roman Empire are represented.
