### ISSUE TITLE
Unable to open military shipyard

### ISSUE THREAD

**Issue by sternstaub** [JustusAvramenko/delenda_est#63]
![image](https://github.com/JustusAvramenko/delenda_est/assets/92979292/68c11f56-c259-4cc1-a34d-b2f9531476bc)
This happens when trying to open the GUI for military shipyard. Which logfiles do you require?

**Comment by JustusAvramenko** [comment]
No need for a log file. I see here that it is a problem with a technology. Not an uncommon bug. Usually a typo in the tech json file. I do it all the time. (lol). Which civ were you playing?
